services:
  web:
    build: .
    restart: always
    environment:
      PORT: 8081
      JDBC_URL: "jdbc:postgresql://db:5432"
      DATABASE: pettcaredb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: AhTn.829.KF!
      JWT_ISSUER: "http://0.0.0.0:8080/"
      JWT_AUDIENCE: "http://0.0.0.0:8080/hierarchy"
      JWT_REALM: "Access to 'hierarchy'"
      JWT_EXPIRATION: 31536000
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pettcaredb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54333:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s